--- #YAML:1.0
name:               App-SimpleScan
version:            3.00
abstract:           simple_scan's core code
author:
    - Joe McMahon <mcmahon@yahoo-inc.com >
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Clone:                0.20
    Encode:               0
    Getopt::Long:         0
    Graph:                0.65
    IO::ScalarArray:      2.110
    Regexp::Common:       0
    Scalar::Util:         0
    Sub::Installer:       0
    Test::Differences:    0
    Test::More:           0
    Test::WWW::Simple:    0.18
    WWW::Mechanize:       1.16
    WWW::Mechanize::Pluggable:  0.09
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
